### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MystieBluz**
ReadMe Draft ... Please review and submit any changes you feel may be needed

### CODE REVIEW

**Review by Bungycode — CHANGES_REQUESTED** [review]
Here is the live url for the links section at the bottom. Add that please.

https://bungycode.github.io/Personal-Assistant/

**Review by MystieBluz — COMMENTED** [review]
Updated ReadMe with Live URL Link

**Review by MystieBluz — COMMENTED** [review]
Updated wording for Major events and cities

**Review by MystieBluz — COMMENTED** [review]
Wording updated

**Review by Bungycode — APPROVED** [review]
Looks good adding now.

**Pull request merged**
